//! Compatibility shims for FFmpeg API renames.
//!
//! FFmpeg 7.0 renamed the codec profile constants from `FF_PROFILE_*` to
//! `AV_PROFILE_*` (the old names were removed, not deprecated). Re-export them
//! under the historical names so call sites stay version-agnostic.

#[cfg(feature = "ffmpeg_7_0")]
pub use crate::ffi::{
	AV_LEVEL_UNKNOWN as FF_LEVEL_UNKNOWN,
	AV_PROFILE_AAC_ELD as FF_PROFILE_AAC_ELD,
	AV_PROFILE_AAC_HE as FF_PROFILE_AAC_HE,
	AV_PROFILE_AAC_HE_V2 as FF_PROFILE_AAC_HE_V2,
	AV_PROFILE_AAC_LD as FF_PROFILE_AAC_LD,
	AV_PROFILE_AAC_LOW as FF_PROFILE_AAC_LOW,
	AV_PROFILE_AAC_LTP as FF_PROFILE_AAC_LTP,
	AV_PROFILE_AAC_MAIN as FF_PROFILE_AAC_MAIN,
	AV_PROFILE_AAC_SSR as FF_PROFILE_AAC_SSR,
	AV_PROFILE_AV1_HIGH as FF_PROFILE_AV1_HIGH,
	AV_PROFILE_AV1_MAIN as FF_PROFILE_AV1_MAIN,
	AV_PROFILE_AV1_PROFESSIONAL as FF_PROFILE_AV1_PROFESSIONAL,
	AV_PROFILE_DTS as FF_PROFILE_DTS,
	AV_PROFILE_DTS_96_24 as FF_PROFILE_DTS_96_24,
	AV_PROFILE_DTS_ES as FF_PROFILE_DTS_ES,
	AV_PROFILE_DTS_EXPRESS as FF_PROFILE_DTS_EXPRESS,
	AV_PROFILE_DTS_HD_HRA as FF_PROFILE_DTS_HD_HRA,
	AV_PROFILE_DTS_HD_MA as FF_PROFILE_DTS_HD_MA,
	AV_PROFILE_H264_BASELINE as FF_PROFILE_H264_BASELINE,
	AV_PROFILE_H264_CAVLC_444 as FF_PROFILE_H264_CAVLC_444,
	AV_PROFILE_H264_CONSTRAINED as FF_PROFILE_H264_CONSTRAINED,
	AV_PROFILE_H264_CONSTRAINED_BASELINE as FF_PROFILE_H264_CONSTRAINED_BASELINE,
	AV_PROFILE_H264_EXTENDED as FF_PROFILE_H264_EXTENDED,
	AV_PROFILE_H264_HIGH as FF_PROFILE_H264_HIGH,
	AV_PROFILE_H264_HIGH_10 as FF_PROFILE_H264_HIGH_10,
	AV_PROFILE_H264_HIGH_10_INTRA as FF_PROFILE_H264_HIGH_10_INTRA,
	AV_PROFILE_H264_HIGH_422 as FF_PROFILE_H264_HIGH_422,
	AV_PROFILE_H264_HIGH_422_INTRA as FF_PROFILE_H264_HIGH_422_INTRA,
	AV_PROFILE_H264_HIGH_444 as FF_PROFILE_H264_HIGH_444,
	AV_PROFILE_H264_HIGH_444_INTRA as FF_PROFILE_H264_HIGH_444_INTRA,
	AV_PROFILE_H264_HIGH_444_PREDICTIVE as FF_PROFILE_H264_HIGH_444_PREDICTIVE,
	AV_PROFILE_H264_INTRA as FF_PROFILE_H264_INTRA,
	AV_PROFILE_H264_MAIN as FF_PROFILE_H264_MAIN,
	AV_PROFILE_HEVC_MAIN as FF_PROFILE_HEVC_MAIN,
	AV_PROFILE_HEVC_MAIN_10 as FF_PROFILE_HEVC_MAIN_10,
	AV_PROFILE_HEVC_MAIN_STILL_PICTURE as FF_PROFILE_HEVC_MAIN_STILL_PICTURE,
	AV_PROFILE_HEVC_REXT as FF_PROFILE_HEVC_REXT,
	AV_PROFILE_JPEG2000_CSTREAM_NO_RESTRICTION as FF_PROFILE_JPEG2000_CSTREAM_NO_RESTRICTION,
	AV_PROFILE_JPEG2000_CSTREAM_RESTRICTION_0 as FF_PROFILE_JPEG2000_CSTREAM_RESTRICTION_0,
	AV_PROFILE_JPEG2000_CSTREAM_RESTRICTION_1 as FF_PROFILE_JPEG2000_CSTREAM_RESTRICTION_1,
	AV_PROFILE_JPEG2000_DCINEMA_2K as FF_PROFILE_JPEG2000_DCINEMA_2K,
	AV_PROFILE_JPEG2000_DCINEMA_4K as FF_PROFILE_JPEG2000_DCINEMA_4K,
	AV_PROFILE_MPEG2_422 as FF_PROFILE_MPEG2_422,
	AV_PROFILE_MPEG2_AAC_HE as FF_PROFILE_MPEG2_AAC_HE,
	AV_PROFILE_MPEG2_AAC_LOW as FF_PROFILE_MPEG2_AAC_LOW,
	AV_PROFILE_MPEG2_HIGH as FF_PROFILE_MPEG2_HIGH,
	AV_PROFILE_MPEG2_MAIN as FF_PROFILE_MPEG2_MAIN,
	AV_PROFILE_MPEG2_SIMPLE as FF_PROFILE_MPEG2_SIMPLE,
	AV_PROFILE_MPEG2_SNR_SCALABLE as FF_PROFILE_MPEG2_SNR_SCALABLE,
	AV_PROFILE_MPEG2_SS as FF_PROFILE_MPEG2_SS,
	AV_PROFILE_MPEG4_ADVANCED_CODING as FF_PROFILE_MPEG4_ADVANCED_CODING,
	AV_PROFILE_MPEG4_ADVANCED_CORE as FF_PROFILE_MPEG4_ADVANCED_CORE,
	AV_PROFILE_MPEG4_ADVANCED_REAL_TIME as FF_PROFILE_MPEG4_ADVANCED_REAL_TIME,
	AV_PROFILE_MPEG4_ADVANCED_SCALABLE_TEXTURE as FF_PROFILE_MPEG4_ADVANCED_SCALABLE_TEXTURE,
	AV_PROFILE_MPEG4_ADVANCED_SIMPLE as FF_PROFILE_MPEG4_ADVANCED_SIMPLE,
	AV_PROFILE_MPEG4_BASIC_ANIMATED_TEXTURE as FF_PROFILE_MPEG4_BASIC_ANIMATED_TEXTURE,
	AV_PROFILE_MPEG4_CORE as FF_PROFILE_MPEG4_CORE,
	AV_PROFILE_MPEG4_CORE_SCALABLE as FF_PROFILE_MPEG4_CORE_SCALABLE,
	AV_PROFILE_MPEG4_HYBRID as FF_PROFILE_MPEG4_HYBRID,
	AV_PROFILE_MPEG4_MAIN as FF_PROFILE_MPEG4_MAIN,
	AV_PROFILE_MPEG4_N_BIT as FF_PROFILE_MPEG4_N_BIT,
	AV_PROFILE_MPEG4_SCALABLE_TEXTURE as FF_PROFILE_MPEG4_SCALABLE_TEXTURE,
	AV_PROFILE_MPEG4_SIMPLE as FF_PROFILE_MPEG4_SIMPLE,
	AV_PROFILE_MPEG4_SIMPLE_FACE_ANIMATION as FF_PROFILE_MPEG4_SIMPLE_FACE_ANIMATION,
	AV_PROFILE_MPEG4_SIMPLE_SCALABLE as FF_PROFILE_MPEG4_SIMPLE_SCALABLE,
	AV_PROFILE_MPEG4_SIMPLE_STUDIO as FF_PROFILE_MPEG4_SIMPLE_STUDIO,
	AV_PROFILE_RESERVED as FF_PROFILE_RESERVED,
	AV_PROFILE_UNKNOWN as FF_PROFILE_UNKNOWN,
	AV_PROFILE_VC1_ADVANCED as FF_PROFILE_VC1_ADVANCED,
	AV_PROFILE_VC1_COMPLEX as FF_PROFILE_VC1_COMPLEX,
	AV_PROFILE_VC1_MAIN as FF_PROFILE_VC1_MAIN,
	AV_PROFILE_VC1_SIMPLE as FF_PROFILE_VC1_SIMPLE,
	AV_PROFILE_VP9_0 as FF_PROFILE_VP9_0,
	AV_PROFILE_VP9_1 as FF_PROFILE_VP9_1,
	AV_PROFILE_VP9_2 as FF_PROFILE_VP9_2,
	AV_PROFILE_VP9_3 as FF_PROFILE_VP9_3,
};

#[cfg(not(feature = "ffmpeg_7_0"))]
pub use crate::ffi::{
	FF_LEVEL_UNKNOWN,
	FF_PROFILE_AAC_ELD,
	FF_PROFILE_AAC_HE,
	FF_PROFILE_AAC_HE_V2,
	FF_PROFILE_AAC_LD,
	FF_PROFILE_AAC_LOW,
	FF_PROFILE_AAC_LTP,
	FF_PROFILE_AAC_MAIN,
	FF_PROFILE_AAC_SSR,
	FF_PROFILE_AV1_HIGH,
	FF_PROFILE_AV1_MAIN,
	FF_PROFILE_AV1_PROFESSIONAL,
	FF_PROFILE_DTS,
	FF_PROFILE_DTS_96_24,
	FF_PROFILE_DTS_ES,
	FF_PROFILE_DTS_EXPRESS,
	FF_PROFILE_DTS_HD_HRA,
	FF_PROFILE_DTS_HD_MA,
	FF_PROFILE_H264_BASELINE,
	FF_PROFILE_H264_CAVLC_444,
	FF_PROFILE_H264_CONSTRAINED,
	FF_PROFILE_H264_CONSTRAINED_BASELINE,
	FF_PROFILE_H264_EXTENDED,
	FF_PROFILE_H264_HIGH,
	FF_PROFILE_H264_HIGH_10,
	FF_PROFILE_H264_HIGH_10_INTRA,
	FF_PROFILE_H264_HIGH_422,
	FF_PROFILE_H264_HIGH_422_INTRA,
	FF_PROFILE_H264_HIGH_444,
	FF_PROFILE_H264_HIGH_444_INTRA,
	FF_PROFILE_H264_HIGH_444_PREDICTIVE,
	FF_PROFILE_H264_INTRA,
	FF_PROFILE_H264_MAIN,
	FF_PROFILE_HEVC_MAIN,
	FF_PROFILE_HEVC_MAIN_10,
	FF_PROFILE_HEVC_MAIN_STILL_PICTURE,
	FF_PROFILE_HEVC_REXT,
	FF_PROFILE_JPEG2000_CSTREAM_NO_RESTRICTION,
	FF_PROFILE_JPEG2000_CSTREAM_RESTRICTION_0,
	FF_PROFILE_JPEG2000_CSTREAM_RESTRICTION_1,
	FF_PROFILE_JPEG2000_DCINEMA_2K,
	FF_PROFILE_JPEG2000_DCINEMA_4K,
	FF_PROFILE_MPEG2_422,
	FF_PROFILE_MPEG2_AAC_HE,
	FF_PROFILE_MPEG2_AAC_LOW,
	FF_PROFILE_MPEG2_HIGH,
	FF_PROFILE_MPEG2_MAIN,
	FF_PROFILE_MPEG2_SIMPLE,
	FF_PROFILE_MPEG2_SNR_SCALABLE,
	FF_PROFILE_MPEG2_SS,
	FF_PROFILE_MPEG4_ADVANCED_CODING,
	FF_PROFILE_MPEG4_ADVANCED_CORE,
	FF_PROFILE_MPEG4_ADVANCED_REAL_TIME,
	FF_PROFILE_MPEG4_ADVANCED_SCALABLE_TEXTURE,
	FF_PROFILE_MPEG4_ADVANCED_SIMPLE,
	FF_PROFILE_MPEG4_BASIC_ANIMATED_TEXTURE,
	FF_PROFILE_MPEG4_CORE,
	FF_PROFILE_MPEG4_CORE_SCALABLE,
	FF_PROFILE_MPEG4_HYBRID,
	FF_PROFILE_MPEG4_MAIN,
	FF_PROFILE_MPEG4_N_BIT,
	FF_PROFILE_MPEG4_SCALABLE_TEXTURE,
	FF_PROFILE_MPEG4_SIMPLE,
	FF_PROFILE_MPEG4_SIMPLE_FACE_ANIMATION,
	FF_PROFILE_MPEG4_SIMPLE_SCALABLE,
	FF_PROFILE_MPEG4_SIMPLE_STUDIO,
	FF_PROFILE_RESERVED,
	FF_PROFILE_UNKNOWN,
	FF_PROFILE_VC1_ADVANCED,
	FF_PROFILE_VC1_COMPLEX,
	FF_PROFILE_VC1_MAIN,
	FF_PROFILE_VC1_SIMPLE,
	FF_PROFILE_VP9_0,
	FF_PROFILE_VP9_1,
	FF_PROFILE_VP9_2,
	FF_PROFILE_VP9_3,
};


/// FFmpeg 8.0 turned the `SWS_*` scaler flags into an `enum SwsFlags`, so bindgen
/// emits them as enum variants rather than bare integer constants. Re-expose them
/// as `c_int` constants under the historical names.
#[cfg(feature = "ffmpeg_8_0")]
mod sws_flags {
	use libc::c_int;

	pub const SWS_FAST_BILINEAR: c_int = crate::ffi::SwsFlags::SWS_FAST_BILINEAR as c_int;
	pub const SWS_BILINEAR: c_int = crate::ffi::SwsFlags::SWS_BILINEAR as c_int;
	pub const SWS_BICUBIC: c_int = crate::ffi::SwsFlags::SWS_BICUBIC as c_int;
	pub const SWS_X: c_int = crate::ffi::SwsFlags::SWS_X as c_int;
	pub const SWS_POINT: c_int = crate::ffi::SwsFlags::SWS_POINT as c_int;
	pub const SWS_AREA: c_int = crate::ffi::SwsFlags::SWS_AREA as c_int;
	pub const SWS_BICUBLIN: c_int = crate::ffi::SwsFlags::SWS_BICUBLIN as c_int;
	pub const SWS_GAUSS: c_int = crate::ffi::SwsFlags::SWS_GAUSS as c_int;
	pub const SWS_SINC: c_int = crate::ffi::SwsFlags::SWS_SINC as c_int;
	pub const SWS_LANCZOS: c_int = crate::ffi::SwsFlags::SWS_LANCZOS as c_int;
	pub const SWS_SPLINE: c_int = crate::ffi::SwsFlags::SWS_SPLINE as c_int;
	pub const SWS_PRINT_INFO: c_int = crate::ffi::SwsFlags::SWS_PRINT_INFO as c_int;
	pub const SWS_FULL_CHR_H_INT: c_int = crate::ffi::SwsFlags::SWS_FULL_CHR_H_INT as c_int;
	pub const SWS_FULL_CHR_H_INP: c_int = crate::ffi::SwsFlags::SWS_FULL_CHR_H_INP as c_int;
	pub const SWS_DIRECT_BGR: c_int = crate::ffi::SwsFlags::SWS_DIRECT_BGR as c_int;
	pub const SWS_ACCURATE_RND: c_int = crate::ffi::SwsFlags::SWS_ACCURATE_RND as c_int;
	pub const SWS_BITEXACT: c_int = crate::ffi::SwsFlags::SWS_BITEXACT as c_int;
	pub const SWS_ERROR_DIFFUSION: c_int = crate::ffi::SwsFlags::SWS_ERROR_DIFFUSION as c_int;
}

#[cfg(feature = "ffmpeg_8_0")]
pub use sws_flags::*;

#[cfg(not(feature = "ffmpeg_8_0"))]
pub use crate::ffi::{
	SWS_FAST_BILINEAR,
	SWS_BILINEAR,
	SWS_BICUBIC,
	SWS_X,
	SWS_POINT,
	SWS_AREA,
	SWS_BICUBLIN,
	SWS_GAUSS,
	SWS_SINC,
	SWS_LANCZOS,
	SWS_SPLINE,
	SWS_PRINT_INFO,
	SWS_FULL_CHR_H_INT,
	SWS_FULL_CHR_H_INP,
	SWS_DIRECT_BGR,
	SWS_ACCURATE_RND,
	SWS_BITEXACT,
	SWS_ERROR_DIFFUSION,
};
